import assert from "node:assert/strict";
import { execFile, execFileSync, spawn } from "node:child_process";
import { createHash } from "node:crypto";
import { once } from "node:events";
import { renameSync } from "node:fs";
import {
  chmod,
  mkdir,
  mkdtemp,
  readFile,
  rm,
  symlink,
  writeFile,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import { resolve } from "node:path";
import test from "node:test";
import { promisify } from "node:util";
import { fileURLToPath } from "node:url";

import {
  buildCargoVendorBundle,
  buildEnvironment,
  canonicalJson,
  cargoConfigurationDifference,
  cargoSourceConfig,
  dangerousCredentialEnvironment,
  encodeFrameHeader,
  openGeneratedBundle,
  parseBuildRequest,
  probeDescriptor,
  resolveFixedCargoExecutable,
  runTool,
  selectVendorDirectories,
  writeCargoVendorFrame,
} from "./ci-pr-cargo-builder.mjs";

const execFileAsync = promisify(execFile);
const helperPath = fileURLToPath(new URL("./ci-pr-cargo-builder.mjs", import.meta.url));
const baseHead = "1".repeat(40);
const pullRequestHead = "2".repeat(40);
const mergeHead = "3".repeat(40);
const gitSource = "git+https://example.test/gitdep?rev=fixture#" + "a".repeat(40);
const cargoLock = `# This file is automatically @generated by Cargo.\nversion = 4\n\n` +
  `[[package]]\nname = "gitdep"\nversion = "1.2.3"\nsource = "${gitSource}"\n\n` +
  `[[package]]\nname = "registry"\nversion = "9.8.7"\n` +
  `source = "registry+https://github.com/rust-lang/crates.io-index"\n` +
  `checksum = "${"b".repeat(64)}"\n`;
const vendorOutput = `[source.crates-io]\nreplace-with = "vendored-sources"\n\n` +
  `[source."git+https://example.test/gitdep?rev=fixture"]\n` +
  `git = "https://example.test/gitdep"\nrev = "fixture"\n` +
  `replace-with = "vendored-sources"\n\n[source.vendored-sources]\n` +
  `directory = "/private/tmp/vendor"\n`;

test("helper accepts only exact canonical identities and side-effect-free invalid build probes", async () => {
  const request = canonicalJson({
    baseHead,
    mergeHead,
    number: 17,
    pullRequestHead,
    version: 1,
  });
  assert.deepEqual(parseBuildRequest(Buffer.from(request)), {
    type: "pull_request",
    version: 1,
    number: 17,
    baseHead,
    pullRequestHead,
    mergeHead,
  });
  assert.throws(
    () => parseBuildRequest(Buffer.from(request + "\n")),
    /canonical JSON/,
  );
  assert.throws(
    () => parseBuildRequest(Buffer.from(JSON.stringify({
      version: 1,
      number: 17,
      baseHead,
      pullRequestHead,
      mergeHead,
    }))),
    /canonical JSON/,
  );
  const invalid = await run(process.execPath, [helperPath, "--build"], {
    PATH: "/usr/bin:/bin",
    LANG: "C.UTF-8",
  }, Buffer.alloc(0));
  assert.equal(invalid.code, 65);
  assert.equal(invalid.stdout.length, 0);
  assert.match(invalid.stderr.toString(), /^Cargo preparation helper failed:/);
  const extra = await run(process.execPath, [helperPath, "--build", "extra"], {
    PATH: "/usr/bin:/bin",
    LANG: "C.UTF-8",
  }, Buffer.alloc(0));
  assert.equal(extra.code, 65);
  assert.equal(extra.stdout.length, 0);
});

test("probe and fresh child environment fail closed on credential authority", async () => {
  assert.deepEqual(probeDescriptor({ env: {}, uid: 502, gid: 20 }), {
    credentialEnvironmentNames: [],
    freshHomePolicy: "per-build-private-temporary",
    gid: 20,
    helperVersion: "2026-08-22.1",
    uid: 502,
    version: 1,
  });
  assert.deepEqual(
    dangerousCredentialEnvironment({
      PATH: "/usr/bin:/bin",
      NANOCODEX_CI_TOKEN: "sentinel-authority",
      SSH_AUTH_SOCK: "/private/agent",
      NODE_OPTIONS: "--trace-warnings",
    }),
    ["NANOCODEX_CI_TOKEN", "NODE_OPTIONS", "SSH_AUTH_SOCK"],
  );
  assert.throws(
    () => probeDescriptor({ env: {}, uid: 502, gid: 0 }),
    /POSIX uid and gid/,
  );
  assert.throws(
    () => probeDescriptor({ env: {}, uid: 0, gid: 20 }),
    /POSIX uid and gid/,
  );
  assert.throws(
    () => probeDescriptor({ env: { NANOCODEX_CI_TOKEN: "sentinel" }, uid: 502, gid: 20 }),
    /credential-dangerous/,
  );

  const directory = await mkdtemp(resolve(tmpdir(), "nanocodex-helper-env-"));
  try {
    const state = {
      root: directory,
      home: resolve(directory, "home"),
      cargoHome: resolve(directory, "cargo-home"),
    };
    const env = buildEnvironment(state);
    assert.equal(env.NANOCODEX_CI_TOKEN, undefined);
    assert.equal(env.HOME, state.home);
    assert.equal(env.CARGO_HOME, state.cargoHome);
    assert.equal(env.GIT_CONFIG_GLOBAL, "/dev/null");
    assert.equal(env.GIT_CONFIG_NOSYSTEM, "1");
    const hostile = await execFileAsync(process.execPath, [
      "--input-type=module",
      "--eval",
      `if (process.env.NANOCODEX_CI_TOKEN) process.exit(91);` +
        `import {spawnSync} from 'node:child_process';` +
        `const r=spawnSync('/usr/bin/security',['find-generic-password','-s',` +
        `'dev.nanocodex.test.nonexistent','-w'],{encoding:'utf8'});` +
        `process.stdout.write(JSON.stringify({token:process.env.NANOCODEX_CI_TOKEN??null,` +
        `security:r.status,canary:(r.stdout??'').trim()}));`,
    ], { env, encoding: "utf8" });
    const observed = JSON.parse(hostile.stdout);
    assert.equal(observed.token, null);
    assert.equal(observed.canary, "");
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
});

test("Cargo resolution accepts only one fixed root-owned real trust chain", async () => {
  const cargo = "/Library/PrivilegedHelperTools/dev.nanocodex.ci-cargo";
  const visited = [];
  const identities = new Map([
    [cargo, fakeIdentity({ file: true, mode: 0o100755, nlink: 1 })],
    ["/Library/PrivilegedHelperTools", fakeIdentity({ mode: 0o40755 })],
    ["/Library", fakeIdentity({ mode: 0o40755 })],
    ["/", fakeIdentity({ mode: 0o40755 })],
  ]);
  const options = {
    realpathPath: async (path) => path,
    lstatPath: async (path) => {
      visited.push(path);
      return identities.get(path);
    },
  };
  assert.equal(await resolveFixedCargoExecutable(options), cargo);
  assert.deepEqual(visited, [cargo, "/Library/PrivilegedHelperTools", "/Library", "/"]);

  for (const [path, identity, pattern] of [
    [cargo, fakeIdentity({ file: true, uid: 501, mode: 0o100755, nlink: 1 }), /root-owned/],
    [cargo, fakeIdentity({ file: true, mode: 0o100755, nlink: 2 }), /singly-linked/],
    ["/Library", fakeIdentity({ mode: 0o40775 }), /parent/],
  ]) {
    const unsafe = new Map(identities);
    unsafe.set(path, identity);
    await assert.rejects(
      resolveFixedCargoExecutable({
        realpathPath: async (value) => value,
        lstatPath: async (value) => unsafe.get(value),
      }),
      pattern,
    );
  }
  await assert.rejects(
    resolveFixedCargoExecutable({
      realpathPath: async () => "/private/var/linked-cargo",
      lstatPath: async (path) => identities.get(path),
    }),
    /must not traverse symbolic links/,
  );
  const source = await readFile(helperPath, "utf8");
  assert.doesNotMatch(source, /\/usr\/local\/bin\/cargo|\/opt\/homebrew\/bin\/cargo|\/usr\/bin\/cargo/);
});

test("Cargo config boundary rejects content, mode, add/remove, and symlink changes", () => {
  const unchanged = new Map([
    [".cargo", `040000 tree ${"a".repeat(40)}`],
    [".cargo/config.toml", `100644 blob ${"b".repeat(40)}`],
  ]);
  assert.equal(cargoConfigurationDifference(unchanged, new Map(unchanged)), null);
  for (const changed of [
    new Map([[".cargo/config.toml", `100644 blob ${"c".repeat(40)}`]]),
    new Map([[".cargo/config.toml", `100755 blob ${"b".repeat(40)}`]]),
    new Map(),
    new Map([[".cargo/config.toml", `120000 blob ${"b".repeat(40)}`]]),
  ]) {
    assert.equal(
      cargoConfigurationDifference(unchanged, changed),
      ".cargo/config.toml",
    );
  }
  assert.equal(
    cargoConfigurationDifference(
      new Map(),
      new Map([[".cargo/config", `100644 blob ${"d".repeat(40)}`]]),
    ),
    ".cargo/config",
  );
});

test("moved deterministic vendor builder binds every locked package and one exact frame", async () => {
  const directory = await mkdtemp(resolve(tmpdir(), "nanocodex-helper-bundle-"));
  try {
    const vendor = resolve(directory, "vendor");
    await writePackage(vendor, "gitdep-1.2.3", null, {
      "Cargo.toml": "[package]\nname='gitdep'\nversion='1.2.3'\n",
      "src/lib.rs": "pub fn git_dependency() {}\n",
    });
    await writePackage(vendor, "registry-9.8.7", "b".repeat(64), {
      "Cargo.toml": "[package]\nname='registry'\nversion='9.8.7'\n",
    });
    const directories = await selectVendorDirectories(vendor, cargoLock);
    assert.deepEqual(directories, ["gitdep-1.2.3", "registry-9.8.7"]);
    const config = cargoSourceConfig(vendorOutput, cargoLock);
    assert.match(config, /directory = "\/workspace\/\.cargo-home\/vendor"/);
    const one = resolve(directory, "one.tar.gz");
    const two = resolve(directory, "two.tar.gz");
    await buildCargoVendorBundle({
      bundlePath: one,
      config,
      directories,
      vendorDirectory: vendor,
    });
    await buildCargoVendorBundle({
      bundlePath: two,
      config,
      directories,
      vendorDirectory: vendor,
    });
    assert.deepEqual(await readFile(one), await readFile(two));
    const bytes = await readFile(one);
    const descriptor = {
      version: 1,
      number: 17,
      baseHead,
      pullRequestHead,
      mergeHead,
      cargoLockBlob: "4".repeat(40),
      key: `cargo-vendor/${"4".repeat(40)}/${sha256(bytes)}/bundle.tar.gz`,
      size: bytes.length,
      sha256: sha256(bytes),
    };
    const frame = Buffer.concat([encodeFrameHeader(descriptor), bytes]);
    assert.equal(frame.length, encodeFrameHeader(descriptor).length + descriptor.size);
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
});

test("generated bundle is hashed and framed from one no-follow fd and detects path replacement", async () => {
  const directory = await mkdtemp(resolve(tmpdir(), "nanocodex-helper-fd-"));
  const bundlePath = resolve(directory, "bundle.tar.gz");
  const replacementPath = resolve(directory, "replacement.tar.gz");
  const movedPath = resolve(directory, "original-moved.tar.gz");
  const bytes = Buffer.from("fixed generated Cargo vendor bytes");
  let bundle;
  try {
    await writeFile(bundlePath, bytes, { mode: 0o600 });
    await chmod(bundlePath, 0o600);
    bundle = await openGeneratedBundle(bundlePath);
    const descriptor = {
      version: 1,
      head: "5".repeat(40),
      cargoLockBlob: "4".repeat(40),
      key: `cargo-vendor/${"4".repeat(40)}/${sha256(bytes)}/bundle.tar.gz`,
      size: bytes.length,
      sha256: sha256(bytes),
    };
    const output = [];
    await writeCargoVendorFrame({ write: (chunk) => (output.push(Buffer.from(chunk)), true) }, descriptor, bundle);
    assert.deepEqual(Buffer.concat(output), Buffer.concat([encodeFrameHeader(descriptor), bytes]));

    await bundle.handle.close();
    bundle = await openGeneratedBundle(bundlePath);
    await writeFile(replacementPath, Buffer.from(bytes), { mode: 0o600 });
    await chmod(replacementPath, 0o600);
    let replaced = false;
    await assert.rejects(
      writeCargoVendorFrame({
        write(chunk) {
          if (!replaced) {
            replaced = true;
            renameSync(bundlePath, movedPath);
            renameSync(replacementPath, bundlePath);
          }
          return true;
        },
      }, descriptor, bundle),
      /bundle (?:has an unsafe identity|changed while framing|path changed)/,
    );
    const linkPath = resolve(directory, "bundle-link.tar.gz");
    await symlink(bundlePath, linkPath);
    await assert.rejects(openGeneratedBundle(linkPath), /ELOOP|symbolic link/i);
  } finally {
    await bundle?.handle.close().catch(() => undefined);
    await rm(directory, { recursive: true, force: true });
  }
});

test("builder rejects successful tool leader exit with a TERM-ignoring detached-stdio descendant", {
  timeout: 10_000,
}, async () => {
  if (process.platform === "win32") return;
  const directory = await mkdtemp(resolve(tmpdir(), "nanocodex-builder-success-group-"));
  const pidPath = resolve(directory, "processes.json");
  const controller = new AbortController();
  let processes;
  let running;
  try {
    running = runTool(process.execPath, [
      "--eval",
      leaderWithTermIgnoringDescendant(pidPath),
    ], {
      cwd: directory,
      env: { LANG: "C.UTF-8", PATH: process.env.PATH ?? "/usr/bin:/bin" },
      signal: controller.signal,
      operation: "builder success fixture",
    });
    processes = await waitForProcessFixture(pidPath);
    await waitForProcessGone(processes.leader);
    assertProcessAlive(processes.descendant);
    await assert.rejects(
      running.catch((cause) => {
        assertProcessDead(processes.descendant);
        throw cause;
      }),
      /left a live detached process-group descendant/,
    );
    await waitForProcessGone(processes.descendant);
  } finally {
    controller.abort(new DOMException("test cleanup", "AbortError"));
    await running?.catch(() => undefined);
    forceKillProcess(processes?.leader);
    forceKillProcess(processes?.descendant);
    await rm(directory, { recursive: true, force: true });
  }
});

test("builder abort after tool leader exit wins and awaits descendant group cleanup", {
  timeout: 10_000,
}, async () => {
  if (process.platform === "win32") return;
  const directory = await mkdtemp(resolve(tmpdir(), "nanocodex-builder-exit-abort-"));
  const pidPath = resolve(directory, "processes.json");
  const controller = new AbortController();
  let processes;
  let running;
  try {
    running = runTool(process.execPath, [
      "--eval",
      leaderWithTermIgnoringDescendant(pidPath),
    ], {
      cwd: directory,
      env: { LANG: "C.UTF-8", PATH: process.env.PATH ?? "/usr/bin:/bin" },
      signal: controller.signal,
      operation: "builder abort fixture",
    });
    processes = await waitForProcessFixture(pidPath);
    await waitForProcessGone(processes.leader);
    assertProcessAlive(processes.descendant);
    controller.abort(new DOMException("builder superseded after leader exit", "AbortError"));
    await assert.rejects(
      running.catch((cause) => {
        assertProcessDead(processes.descendant);
        throw cause;
      }),
      (cause) =>
        cause?.name === "AbortError" &&
        cause.message === "builder superseded after leader exit",
    );
    await waitForProcessGone(processes.descendant);
  } finally {
    controller.abort(new DOMException("test cleanup", "AbortError"));
    await running?.catch(() => undefined);
    forceKillProcess(processes?.leader);
    forceKillProcess(processes?.descendant);
    await rm(directory, { recursive: true, force: true });
  }
});

const keychainConfigured =
  process.platform === "darwin" &&
  process.env.NANOCODEX_CI_DARWIN_TWO_UID_CANARY === "1" &&
  typeof process.env.NANOCODEX_CI_DARWIN_CANARY_SERVICE === "string" &&
  typeof process.env.NANOCODEX_CI_DARWIN_CANARY_ACCOUNT === "string" &&
  typeof process.env.NANOCODEX_CI_PR_PREP_USER === "string";

test("opt-in Darwin two-UID Keychain canary is inaccessible to prep", {
  skip: keychainConfigured ? false : "requires explicit Darwin two-UID Keychain canary configuration",
}, async () => {
  const service = process.env.NANOCODEX_CI_DARWIN_CANARY_SERVICE;
  const account = process.env.NANOCODEX_CI_DARWIN_CANARY_ACCOUNT;
  const prep = process.env.NANOCODEX_CI_PR_PREP_USER;
  const owner = await execFileAsync("/usr/bin/security", [
    "find-generic-password", "-s", service, "-a", account, "-w",
  ], { encoding: "utf8", maxBuffer: 4_096 });
  const canary = owner.stdout.trim();
  assert.ok(canary.length > 0);
  const attempted = await run("/usr/bin/sudo", [
    "-n", "-u", prep, "--", "/usr/bin/security",
    "find-generic-password", "-s", service, "-a", account, "-w",
  ], { PATH: "/usr/bin:/bin", LANG: "C" }, Buffer.alloc(0));
  assert.notEqual(attempted.code, 0);
  assert.equal(attempted.stdout.includes(Buffer.from(canary)), false);
});

function leaderWithTermIgnoringDescendant(pidPath) {
  const descendant = [
    'const {writeFileSync}=require("node:fs");',
    'process.on("SIGTERM",()=>{});',
    `writeFileSync(${JSON.stringify(pidPath)},JSON.stringify({leader:process.ppid,descendant:process.pid}));`,
    "setInterval(()=>{},1000);",
  ].join("");
  return [
    'const {spawn}=require("node:child_process");',
    'const {existsSync}=require("node:fs");',
    `const descendant=spawn(process.execPath,["--eval",${JSON.stringify(descendant)}],{stdio:"ignore"});`,
    "descendant.unref();",
    "const deadline=Date.now()+5000;",
    "const ready=setInterval(()=>{",
    `if(existsSync(${JSON.stringify(pidPath)})){clearInterval(ready);}`,
    "else if(Date.now()>=deadline){clearInterval(ready);process.exitCode=97;}",
    "},5);",
  ].join("");
}

async function waitForProcessFixture(path) {
  for (let attempt = 0; attempt < 500; attempt += 1) {
    try {
      const value = JSON.parse(await readFile(path, "utf8"));
      if (
        Number.isSafeInteger(value?.leader) && value.leader > 0 &&
        Number.isSafeInteger(value?.descendant) && value.descendant > 0
      ) return value;
    } catch {}
    await new Promise((resolvePromise) => setTimeout(resolvePromise, 10));
  }
  throw new Error("process-group fixture did not become ready");
}

async function waitForProcessGone(pid) {
  for (let attempt = 0; attempt < 500; attempt += 1) {
    try {
      process.kill(pid, 0);
    } catch (cause) {
      if (cause?.code === "ESRCH") return;
      throw cause;
    }
    await new Promise((resolvePromise) => setTimeout(resolvePromise, 10));
  }
  throw new Error(`process ${pid} remained alive`);
}

function assertProcessAlive(pid) {
  assert.doesNotThrow(() => process.kill(pid, 0));
}

function assertProcessDead(pid) {
  try {
    process.kill(pid, 0);
  } catch (cause) {
    if (cause?.code === "ESRCH") return;
    throw cause;
  }
  let state;
  try {
    state = execFileSync("/bin/ps", ["-o", "state=", "-p", String(pid)], {
      encoding: "utf8",
    }).trim();
  } catch (cause) {
    if (cause?.status === 1) return;
    throw cause;
  }
  assert.match(state, /^Z/, `process ${pid} remained live in state ${state}`);
}

function forceKillProcess(pid) {
  if (!Number.isSafeInteger(pid) || pid <= 0) return;
  try {
    process.kill(pid, "SIGKILL");
  } catch (cause) {
    if (cause?.code !== "ESRCH") throw cause;
  }
}

async function writePackage(vendor, name, packageHash, files) {
  const root = resolve(vendor, name);
  await mkdir(root, { recursive: true });
  await writeFile(
    resolve(root, ".cargo-checksum.json"),
    JSON.stringify({ files: {}, package: packageHash }),
  );
  for (const [path, body] of Object.entries(files)) {
    await mkdir(resolve(root, path, ".."), { recursive: true });
    await writeFile(resolve(root, path), body);
  }
}

async function run(command, args, env, input) {
  const child = spawn(command, args, {
    env,
    stdio: ["pipe", "pipe", "pipe"],
  });
  const stdout = [];
  const stderr = [];
  child.stdout.on("data", (chunk) => stdout.push(chunk));
  child.stderr.on("data", (chunk) => stderr.push(chunk));
  child.stdin.end(input);
  const [code] = await once(child, "close");
  return { code, stdout: Buffer.concat(stdout), stderr: Buffer.concat(stderr) };
}

function sha256(bytes) {
  return createHash("sha256").update(bytes).digest("hex");
}

function fakeIdentity({ file = false, uid = 0, gid = 0, mode, nlink = 2 }) {
  return {
    uid,
    gid,
    mode,
    nlink,
    isFile: () => file,
    isDirectory: () => !file,
    isSymbolicLink: () => false,
  };
}
