import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import { createHash } from "node:crypto";
import { once } from "node:events";
import { chmod, mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { createServer } from "node:http";
import { tmpdir } from "node:os";
import { resolve } from "node:path";
import { test } from "node:test";
import { promisify } from "node:util";
import { fileURLToPath } from "node:url";

import {
  buildCargoVendorBundle,
  cargoGitSourceConfig,
  readCleanCargoGitCheckouts,
  selectGitVendorDirectories,
} from "./publish-ci-cargo-vendor.mjs";

const execFileAsync = promisify(execFile);
const publisherPath = fileURLToPath(
  new URL("./publish-ci-cargo-vendor.mjs", import.meta.url),
);
const gitSource = "git+https://example.test/gitdep?rev=0123456789abcdef#" + "a".repeat(40);
const cargoLock = `# This file is automatically @generated by Cargo.\nversion = 4\n\n` +
  `[[package]]\nname = "gitdep"\nversion = "1.2.3"\nsource = "${gitSource}"\n`;
const vendorOutput = `To use vendored sources, add this to your config:\n\n` +
  `[source.crates-io]\nreplace-with = "vendored-sources"\n\n` +
  `[source."git+https://example.test/gitdep?rev=0123456789abcdef"]\n` +
  `git = "https://example.test/gitdep"\nrev = "0123456789abcdef"\n` +
  `replace-with = "vendored-sources"\n\n[source.vendored-sources]\n` +
  `directory = "/temporary/vendor"\n`;

test("selects only git packages and builds a deterministic Cargo-home bundle", async () => {
  const directory = await mkdtemp(resolve(tmpdir(), "nanocodex-cargo-vendor-unit-"));
  try {
    const vendor = resolve(directory, "vendor");
    await writePackage(vendor, "gitdep-1.2.3", null, {
      "Cargo.toml": "[package]\nname = \"gitdep\"\nversion = \"1.2.3\"\n",
      "src/lib.rs": "pub fn git_dependency() {}\n",
    });
    await writePackage(vendor, "registry-9.8.7", "b".repeat(64), {
      "Cargo.toml": "[package]\nname = \"registry\"\nversion = \"9.8.7\"\n",
    });
    const selected = await selectGitVendorDirectories(vendor, cargoLock);
    assert.deepEqual(selected, ["gitdep-1.2.3"]);
    const config = cargoGitSourceConfig(vendorOutput, cargoLock);
    assert.doesNotMatch(config, /crates-io/);
    assert.match(config, /git\+https:\/\/example\.test\/gitdep/);
    assert.match(config, /directory = "\/workspace\/\.cargo-home\/vendor"/);

    const one = resolve(directory, "one.tar.gz");
    const two = resolve(directory, "two.tar.gz");
    const init = resolve(directory, "extra-init");
    await mkdir(resolve(init, "src"), { recursive: true });
    await writeFile(resolve(init, "Cargo.toml"), "[package]\nname = \"extra-init\"\n");
    await writeFile(resolve(init, "src/main.rs"), "fn main() {}\n");
    const extraDirectories = [{ sourcePath: init, archivePath: "init" }];
    await buildCargoVendorBundle({
      bundlePath: one,
      config,
      directories: selected,
      extraDirectories,
      vendorDirectory: vendor,
    });
    await buildCargoVendorBundle({
      bundlePath: two,
      config,
      directories: selected,
      extraDirectories,
      vendorDirectory: vendor,
    });
    assert.deepEqual(await readFile(one), await readFile(two));
    const { stdout: listing } = await execFileAsync("tar", ["-tzf", one], {
      encoding: "utf8",
    });
    assert.deepEqual(listing.trimEnd().split("\n"), [
      "config.toml",
      "init/",
      "init/Cargo.toml",
      "init/src/",
      "init/src/main.rs",
      "vendor/",
      "vendor/gitdep-1.2.3/",
      "vendor/gitdep-1.2.3/.cargo-checksum.json",
      "vendor/gitdep-1.2.3/Cargo.toml",
      "vendor/gitdep-1.2.3/src/",
      "vendor/gitdep-1.2.3/src/lib.rs",
    ]);
    assert.doesNotMatch(listing, /registry-9\.8\.7/);
    const { stdout: archivedConfig } = await execFileAsync(
      "tar",
      ["-xOzf", one, "config.toml"],
      { encoding: "utf8" },
    );
    assert.equal(archivedConfig, config);
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
});

test("operator authenticates immutable upload and reuses an existing lock bundle", async () => {
  const directory = await mkdtemp(resolve(tmpdir(), "nanocodex-cargo-vendor-cli-"));
  const repository = resolve(directory, "repo");
  const dependency = resolve(directory, "dependency");
  const cargoHome = resolve(directory, "cargo-home");
  const bin = resolve(directory, "bin");
  const countPath = resolve(directory, "cargo-count");
  const requests = [];
  let published = null;
  const server = createServer(async (request, response) => {
    const chunks = [];
    for await (const chunk of request) chunks.push(chunk);
    const body = Buffer.concat(chunks);
    requests.push({
      authorization: request.headers.authorization,
      body,
      method: request.method,
      url: request.url,
      sha256: request.headers["x-nanocodex-sha256"],
    });
    if (request.method === "HEAD" && request.url?.startsWith("/api/ci/cargo-vendor/")) {
      if (!published) return response.writeHead(404).end();
      response.writeHead(200, {
        "content-length": String(published.size),
        "x-nanocodex-cargo-lock": published.cargoLockBlob,
        "x-nanocodex-key": published.key,
        "x-nanocodex-sha256": published.sha256,
      }).end();
      return;
    }
    if (request.method === "PUT" && request.url?.startsWith("/api/ci/cargo-vendor/")) {
      const cargoLockBlob = request.url.split("/")[4];
      published = {
        key: `cargo-vendor/${cargoLockBlob}/bundle.tar.gz`,
        cargoLockBlob,
        size: body.byteLength,
        sha256: sha256(body),
        uploaded: true,
      };
      response.writeHead(200, { "content-type": "application/json" });
      response.end(JSON.stringify(published));
      return;
    }
    response.writeHead(418).end();
  });
  try {
    await execFileAsync("git", ["init", "-q", "-b", "master", dependency]);
    await execFileAsync("git", ["config", "user.name", "Nanocodex Test"], { cwd: dependency });
    await execFileAsync("git", ["config", "user.email", "test@nanocodex.invalid"], {
      cwd: dependency,
    });
    await writeFile(resolve(dependency, "Cargo.toml"),
      "[package]\nname = \"gitdep\"\nversion = \"1.2.3\"\n");
    await mkdir(resolve(dependency, "src"));
    await writeFile(resolve(dependency, "src/lib.rs"), "pub fn dependency() {}\n");
    await execFileAsync("git", ["add", "."], { cwd: dependency });
    await execFileAsync("git", ["commit", "-qm", "dependency"], { cwd: dependency });
    const dependencyRevision = (await execFileAsync("git", ["rev-parse", "HEAD"], {
      cwd: dependency,
      encoding: "utf8",
    })).stdout.trim();
    const fixtureCargoLock = cargoLock.replace("a".repeat(40), dependencyRevision);
    const checkout = resolve(
      cargoHome,
      "git/checkouts/gitdep-fixture",
      dependencyRevision.slice(0, 7),
    );
    await mkdir(resolve(checkout, ".."), { recursive: true });
    await execFileAsync("git", ["clone", "-q", dependency, checkout]);
    await writeFile(resolve(checkout, ".cargo-ok"), "");
    await execFileAsync("git", ["config", "core.worktree", dependency], { cwd: checkout });
    await assert.rejects(
      readCleanCargoGitCheckouts(fixtureCargoLock, { CARGO_HOME: cargoHome }),
      /rejects local Git configuration: core.worktree/,
    );
    await execFileAsync("git", ["config", "--unset", "core.worktree"], { cwd: checkout });
    assert.equal((await readCleanCargoGitCheckouts(fixtureCargoLock, {
      CARGO_HOME: cargoHome,
    })).length, 1);
    await writeFile(resolve(checkout, "untracked.rs"), "untrusted\n");
    await assert.rejects(
      readCleanCargoGitCheckouts(fixtureCargoLock, { CARGO_HOME: cargoHome }),
      /dirty or mismatched/,
    );
    await rm(resolve(checkout, "untracked.rs"));

    await execFileAsync("git", ["init", "-q", "-b", "master", repository]);
    await execFileAsync("git", ["config", "user.name", "Nanocodex Test"], { cwd: repository });
    await execFileAsync("git", ["config", "user.email", "test@nanocodex.invalid"], {
      cwd: repository,
    });
    await writeFile(resolve(repository, "Cargo.toml"), "[workspace]\nresolver = \"3\"\n");
    await writeFile(resolve(repository, "Cargo.lock"), fixtureCargoLock);
    await execFileAsync("git", ["add", "."], { cwd: repository });
    await execFileAsync("git", ["commit", "-qm", "fixture"], { cwd: repository });
    const cargoLockBlob = (await execFileAsync("git", ["rev-parse", "HEAD:Cargo.lock"], {
      cwd: repository,
      encoding: "utf8",
    })).stdout.trim();

    await mkdir(bin);
    const fakeCargo = resolve(bin, "cargo");
    await writeFile(fakeCargo, `#!/usr/bin/env node
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
const count = ${JSON.stringify(countPath)};
let value = 0;
try { value = Number(readFileSync(count, "utf8")); } catch {}
writeFileSync(count, String(value + 1));
const vendor = process.argv.at(-1);
const git = resolve(vendor, "gitdep-1.2.3");
const registry = resolve(vendor, "registry-9.8.7");
mkdirSync(resolve(git, "src"), { recursive: true });
mkdirSync(registry, { recursive: true });
writeFileSync(resolve(git, ".cargo-checksum.json"), '{"files":{},"package":null}');
writeFileSync(resolve(git, "Cargo.toml"), '[package]\\nname="gitdep"\\nversion="1.2.3"\\n');
writeFileSync(resolve(git, "src/lib.rs"), 'pub fn dependency() {}\\n');
writeFileSync(resolve(registry, ".cargo-checksum.json"), '{"files":{},"package":"${"b".repeat(64)}"}');
process.stdout.write(${JSON.stringify(vendorOutput)});
`);
    await chmod(fakeCargo, 0o755);
    server.listen(0, "127.0.0.1");
    await once(server, "listening");
    const address = server.address();
    assert.ok(address && typeof address === "object");
    const env = {
      ...process.env,
      PATH: `${bin}:${process.env.PATH}`,
      CARGO_HOME: cargoHome,
      NANOCODEX_CI_ORIGIN: `http://127.0.0.1:${address.port}`,
      NANOCODEX_CI_TOKEN: "vendor-token",
      NANOCODEX_REPO: repository,
    };
    const first = await execFileAsync(process.execPath, [publisherPath], {
      env,
      encoding: "utf8",
    });
    assert.match(first.stdout, /Published CI Cargo vendor/);
    assert.equal(await readFile(countPath, "utf8"), "1");
    assert.ok(published);
    assert.equal(published.cargoLockBlob, cargoLockBlob);
    const upload = requests.find(({ method }) => method === "PUT");
    assert.equal(upload.authorization, "Bearer vendor-token");
    assert.equal(upload.sha256, sha256(upload.body));

    const secondStart = requests.length;
    const second = await execFileAsync(process.execPath, [publisherPath], {
      env,
      encoding: "utf8",
    });
    assert.match(second.stdout, /CI Cargo vendor is current/);
    assert.equal(await readFile(countPath, "utf8"), "1", "cargo vendor must not run again");
    assert.deepEqual(
      requests.slice(secondStart).map(({ method, url }) => ({ method, url })),
      [{
        method: "HEAD",
        url: `/api/ci/cargo-vendor/${cargoLockBlob}/bundle.tar.gz`,
      }],
    );
    assert.ok(requests.every(({ authorization }) => authorization === "Bearer vendor-token"));
  } finally {
    if (server.listening) await new Promise((done) => server.close(done));
    await rm(directory, { recursive: true, force: true });
  }
});

async function writePackage(vendor, name, packageHash, files) {
  const root = resolve(vendor, name);
  await mkdir(root, { recursive: true });
  await writeFile(
    resolve(root, ".cargo-checksum.json"),
    JSON.stringify({ files: {}, package: packageHash }),
  );
  for (const [path, body] of Object.entries(files)) {
    await mkdir(resolve(root, path, ".."), { recursive: true });
    await writeFile(resolve(root, path), body);
  }
}

function sha256(body) {
  return createHash("sha256").update(body).digest("hex");
}
