[target.aarch64-apple-darwin]
linker = "/usr/bin/clang"

[target.aarch64-unknown-linux-musl]
linker = "scripts/aarch64-unknown-linux-musl-linker"

[target.x86_64-apple-darwin]
linker = "/usr/bin/clang"
